trigger:
  batch: true
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

jobs:
- job:
  steps:

  - task: AzureCLI@2
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment group create \
          --name $(Build.BuildNumber) \
          --resource-group $(ResourceGroupName) \
          --template-file deploy/main.bicep \
          --parameters environmentType=$(EnvironmentType)